title: Read The Docs Jekyll Theme
description: Port of the Read the Docs theme to Jekyll to use with GitHub Pages.
remote_theme: jekyll-theme-rtd

# Theme settings:
site_author: Manifold Tech
repo_url: "https://github.com/WilliamTsang-MT/manifoldtech.wiki.github.io"
edit_on_github: true
github_docs_folder: true
sticky_navigation: true
prev_next_buttons_location: bottom
search_enabled: true
hljs_style: github-gist
